### ISSUE TITLE
Prometheus

### ISSUE THREAD

**Issue by LogiEx7** [systemli/ansible-role-jitsi-meet-exporter#1]
What is ur prometheus config ?

**Comment by bryanasdev000** [comment]
This is what I use:

```yaml

global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'prometheus'

rule_files:
  - '/etc/prometheus/rules/alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "localhost:9093"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
         - targets: ['localhost:9090']
  - job_name: 'alertmanager'
    static_configs:
         - targets: ['localhost:9093']
  - job_name: 'grafana'
    static_configs:
         - targets: ['localhost:3000']
  - job_name: 'node-exporter'
    static_configs:
            - targets: ['10.108.0.3:9100','localhost:9100']
  - job_name: 'jitsi-exporter'
    static_configs:
         - targets: ['10.108.0.3:9888']

```
